### ISSUE TITLE
fcAPI.fcMP4AddVideoFramePixels - very bad performance

### ISSUE THREAD

**Issue by robochase6000** [unity3d-jp/FrameCapturer#15] opened 2017-06-06 17:40 UTC
i was using an old version of this plugin that used "fcAPI.fcMP4AddVideoFrameTexture" to capture video.  this seemed to work really well.

i updated to the latest yesterday, and this new method seems to be destroying my framerate after 1 second of recording - fcAPI.fcMP4AddVideoFramePixels.  like my vr game goes down from 90fps to <1 fps.

any idea what's going on here?

**Comment by t-mat** [comment] 2017-06-06 18:08
@robochase6000, could you provide minimal repro for your issue?
If we have minimal repro Unity project, we can avoid "it works/does't work on my computer" problem.

**Comment by robochase6000** [comment] 2017-06-06 22:14
hmm. i think this might be related to choosing to setting the 'Output Dir' to 'Data Path'.  it looks like using this option saves the video into your Assets folder.  I think the slow down is actually unity reimporting the movie each frame it is updated, perhaps?

**Comment by i-saint** [comment] 2017-06-06 23:01
there was a problem in old version that in some cases (i.e. many cameras in the scene) capture fails and generate noise image. (I think) it was fixed in recent version with the sacrifice of performance, as you noticed. I will revive old  "fast but possibly unstable" way as an option.

**Closed** 2017-06-09 16:38 UTC

**Comment by i-saint** [comment] 2017-07-21 14:28
https://github.com/unity3d-jp/FrameCapturer/issues/19 probably same issue, but I can't reproduce yet.
